version: "3"

services:

  frontman:
    build:
      dockerfile: docker/frontman.Dockerfile
      context: ../../
    image: frontman
    ports:
      - "3000:3000"
    volumes:
      - ./demo.toml:/frontman.toml:ro

  origin-1:
    build:
      dockerfile: docker/origin.Dockerfile
      context: ../../
    image: origin
    ports:
      - "9999:9999"

  origin-2:
    build:
      dockerfile: docker/origin.Dockerfile
      context: ../../
    image: origin
    ports:
      - "10000:9999"
